### ISSUE TITLE
The "Open in Gitpod" button does not work.

### ISSUE THREAD

**Issue by omasseau** [jeanphibaconnais/template-quarkus#5]
Hello

I tried to click on the "Open in Gitpod" button, but I got this error : 
![image](https://user-images.githubusercontent.com/11772429/181915361-1554faab-1855-442c-8c96-3024f1e4115c.png)

**Comment by jeanphibaconnais** [comment]
Hello @omasseau , oh yes, at the beginning I imagined this repo going to the GitPod repository template. But this is not the case so I change the link right now.

**Comment by jeanphibaconnais** [comment]
This is corrected in this PR https://github.com/jeanphibaconnais/template-quarkus/pull/6.
Thanks for your issue and sorry for this mistake 🙏
